spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(6t8cuFsP4IL07jRxjvYcY2zVO/Fh5LMWXMTbPh3RZnEFa7chDzTe/80anPfOAQfAOaTPr47dfEI2T5qRzzrruwROBzp+r6u7IfEC22I8oNx8e4XFsBhlqmoF4saxa5A8eohrsL2kOmyTX0hJdz5HskC2BqEddPsRYk907flVCPKZJmUoHr4jfyyMSLnTj1IZEQeZX67G2dz1gxTd6Oj/GeslJFsyQ33W35RkInUXdtf7iLjz8PvOZwoeOQNfjTQZ)
    username: ENC(6A8KdGr8isuaib/qeKStgHxIqf7LFQYqSlx3kSJVcLRPzBckVAPwwjo+FgTyspOq)
    password: ENC(AeVzWxViGUUWAH15gR3nsU8TV4cm377IZ63VX9UF26lDvajLdxC0YGM/u+qS5vCg)
    hikari:
      connection-timeout: 600000 #最大超时时间
      maximum-pool-size: 500 #连接数
      max-lifetime: 32000 #控制池中连接的最大生存期
      minimum-idle: 20 #此属性控制 HikariCP尝试在池中维护的最小空闲连接数
      validation-timeout: 3000 #此属性控制测试连接是否活跃的最长时间。此值必须小于 connectionTimeout
      idle-timeout: 60000 #此属性控制允许连接在池中处于空闲状态的最长时间
  mvc:
    format:
      date: yyyy-MM-dd
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    host: ENC(7ezzNNAIcUT5PsLR2T9sGrDUi9YV1xQYvLBou84hMoDzHt5aWS9CRvIV8BLvd0No)
    port: 6379
    password: ENC(UQ6DirhVFB1iSs5ucqNcTpiTeKxQSVXFhrIGiP60G2HeEWYyjeIpSGCzDuLZP03l)
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${file-upload-path}
server:
  servlet:
    encoding:
      charset: utf-8
  port: 3366

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.example.mybatisplus.mapper: debug
file-upload-path: ./file

file:
  upload:
    dir: D:\online_shopping_mall\
