spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-f9kr59fc.sql.tencentcdb.com:20328/online_shopping_mall?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: test
    password: Test1234
  mvc:
    format:
      date: yyyy-MM-dd
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    host: 47.113.225.99
    port: 6379
    password: 123456
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${file-upload-path}
server:
  servlet:
    encoding:
      charset: utf-8
  port: 3366

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.example.mybatisplus.mapper: debug
file-upload-path: ./file

file:
  upload:
    dir: D:/online_shopping_mall/
