spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-f9kr59fc.sql.tencentcdb.com:20328/online_shopping_mall?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: test
    password: Test1234
  mvc:
    format:
      date: yyyy-MM-dd
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  servlet:
    encoding:
      charset: utf-8
  port: 8888

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml

logging:
  level:
    com.example.mybatisplus.mapper: debug
file-upload-path: ./file
